# Generated by Django 4.0.8 on 2022-12-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='users'),
        ),
    ]
