# Generated by Django 4.0.8 on 2022-12-11 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('is_first', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='posts.posts')),
            ],
            options={
                'db_table': 'media',
                'managed': True,
            },
        ),
    ]
