# Generated by Django 4.0.8 on 2022-12-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
