# Generated by Django 4.0.8 on 2022-12-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_posts_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'managed': True, 'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
